[build-system]
requires = ["setuptools", "wheel", "Cython"]

[tool.setuptools]
py-modules = []

[project]
name = "dubins"
version = "1.0.1"
description  = "Code to generate and manipulate dubins curves"